### ISSUE TITLE
Inhomogeneous argument name in cocoa.py and covid19.py

### ISSUE THREAD

**Issue by tjbtjbtjb** [tjbtjbtjb/CoCoA#16]
For the same argument, it's called :
 - 'location' in `covid19.py` and 'where' in `cocoa.py`
 - 'type' in `covid19.py` and 'what' in `cocoa.py`
 - ... ? 
That's disturbing

**Comment by odadoun** [comment]
I have decided that 'where' is for cocoa.py and 'location' for all other method. We can discuss it but let say for this version we freeze it like this
