### ISSUE TITLE
Cannot create a map for 'confirmed' cases 

### ISSUE THREAD

**Issue by tjbtjbtjb** [tjbtjbtjb/CoCoA#19]
See screenshot. Got a KeyError. Not even a CocoaKeyError meaning that this error is not managed by the cocoa framework.
![Screenshot from 2020-11-13 18-09-48](https://user-images.githubusercontent.com/6871008/99100058-969eff00-25db-11eb-82b9-02342e09ca5c.png)

**Comment by odadoun** [comment]
it was in debugging mode, problem fixed
