### ISSUE TITLE
the what='diff' does not work anymore within the front-end framework

### ISSUE THREAD

**Issue by tjbtjbtjb** [tjbtjbtjb/CoCoA#21]
e.g. with cc.plot(where=['FR','Italy'],which='confirmed',what='diff')

See screenhost.

Moreover, what keywords should be cleaned up.

![Screenshot from 2020-11-15 12-12-27](https://user-images.githubusercontent.com/6871008/99183413-dbda4280-273b-11eb-8220-64e43194d873.png)

**Comment by odadoun** [comment]
what='cumul' is the same as no what variable given since jhu give already the cumul value
