### ISSUE TITLE
'daily' and 'weekly' options exist but create bug in cocoa.cocoa

### ISSUE THREAD

**Issue by tjbtjbtjb** [tjbtjbtjb/CoCoA#23]
![Screenshot from 2020-11-15 15-34-34](https://user-images.githubusercontent.com/6871008/99187641-27024e80-2758-11eb-83da-a62c07799490.png)

**Comment by odadoun** [comment]
daily et weekly renvoient quoi au juste pour le plot ??

**Comment by tjbtjbtjb** [comment]
un bug. 
Still not working despite the latest commit
