### ISSUE TITLE
add cocoa.__version__

### ISSUE THREAD

**Issue by odadoun** [tjbtjbtjb/CoCoA#26]
and we need to start this next release ...

**Comment by tjbtjbtjb** [comment]
It's in the `setup.py` file of the package. Isn't it enough ?

**Comment by tjbtjbtjb** [comment]
Done.

![Screenshot from 2020-11-16 14-27-26](https://user-images.githubusercontent.com/6871008/99257816-e538dd00-2817-11eb-9a60-146cc4a981c7.png)
