### ISSUE TITLE
'world' from 'cocoa' 

### ISSUE THREAD

**Issue by odadoun** [tjbtjbtjb/CoCoA#27]
from cocoa import world as cw

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-b18e55bac5a9> in <module>
----> 1 from cocoa import world as cw

ImportError: cannot import name 'world' from 'cocoa' (../cocoa/__init__.py)

**Comment by tjbtjbtjb** [comment]
No more "world" in the 1.0 version. Use a previous one if needed.
