### ISSUE TITLE
Can we have a default quiet output for frontend ?

### ISSUE THREAD

**Issue by tjbtjbtjb** [tjbtjbtjb/CoCoA#4]
Currently, there's 2 lines of unnecessary output

![Screenshot from 2020-07-21 21-44-12](https://user-images.githubusercontent.com/6871008/88100268-9ac28f00-cb9c-11ea-8339-f1101310ecab.png)

**Comment by odadoun** [comment]
When you work directly through a notebook it is useful to know which data are available ...

**Comment by tjbtjbtjb** [comment]
Solved.
Use
```
import cocoa.verb as cv
cv._verbose_mode=2
```
to set the verbose mode : 

- 2 for debug
- 1 for standard output
- 0 for quiet
